name: Dispatch - Test Build Publish

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Build package with Poetry
        run: poetry build

      - name: Upload built package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-artifacts
          path: dist
          retention-days: 1

  publish:
    needs: test-build
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/project/quantcrypt/

    permissions:
      id-token: write

    steps:
      - name: Download built package artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
